openapi: 3.1.0
info:
  title: Drover API
  description: |-
    This is the API used to control the Drover product.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
tags:
  - name: Printer
    description: Controls for the printer
  - name: Device
    description: Controls for the printer
paths:
  /printer/{printerId}:
    get:
      tags:
        - Printer
      summary: Get printer details
      description: Returns printer details
      operationId: getPrinterById
      parameters:
        - name: printerId
          in: path
          description: ID of the printer to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Printer'
        '400':
          description: Printer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Printer:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              required:
                - id
                - printer_name
                - printer_model
                - network_based
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  examples: [1]
                printer_name:
                  type: string
                  examples: [Orange Prusa Mini]
                # tags:
                #   type: array
                #   xml:
                #     wrapped: true
                #   examples: [room1]
                printer_model:
                  type: string
                  description: model of the printer
                  enum:
                    - prusamini
                    - upmini
                    - sailfish
                network_based:
                  type: boolean
                  examples: [true]
                address:
                  type: string
                  examples: [192.168.1.132]
                authentication:
                  type: string
                  examples: [test1234]
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: model of the printer
          enum:
            - PrinterNotFound
    Response:
      required:
        - status
      type: object
      properties:
        status:
          type: object
          required:
            - code
            - statusType
          properties:
            code:
              type: integer
              format: int32
              description: Error code
            statusType:
              type: string
              description: model of the printer